### PR TITLE
Bml fix snippet parsing

### PR DESCRIPTION
**Pull request by ldrbrandon**
Fixed snippet formatting/creation, no more double whitespaces between divs and no more random words getting combined.

### CODE REVIEW

**Comment by ldrbrandon** [comment]
juliancasablancasfingerguns

**Comment by danbender** [comment]
giphy

**Comment by smart-alek** [comment]
Nice work, dude. Is this deployed to Heroku?

**Comment by ldrbrandon** [comment]
Thanks! 

I don't thinkso. Gotta tell JTR

**Pull request merged**
